package com.incognia.feedback;

public enum FeedbackEvent {
  SIGNUP_ACCEPTED,
  SIGNUP_DECLINED,
  PAYMENT_ACCEPTED,
  PAYMENT_ACCEPTED_BY_THIRD_PARTY,
  PAYMENT_ACCEPTED_BY_CONTROL_GROUP,
  PAYMENT_DECLINED,
  PAYMENT_DECLINED_BY_RISK_ANALYSIS,
  PAYMENT_DECLINED_BY_MANUAL_REVIEW,
  PAYMENT_DECLINED_BY_BUSINESS,
  PAYMENT_DECLINED_BY_ACQUIRER,
  LOGIN_ACCEPTED,
  LOGIN_ACCEPTED_BY_DEVICE_VERIFICATION,
  LOGIN_ACCEPTED_BY_FACIAL_BIOMETRICS,
  LOGIN_ACCEPTED_BY_MANUAL_REVIEW,
  LOGIN_DECLINED,
  LOGIN_DECLINED_BY_FACIAL_BIOMETRICS,
  LOGIN_DECLINED_BY_MANUAL_REVIEW,
  ACCOUNT_ALLOWED,
  DEVICE_ALLOWED,
  VERIFIED,
  IDENTITY_FRAUD,
  ACCOUNT_TAKEOVER,
  CHARGEBACK_NOTIFICATION,
  CHARGEBACK,
  PROMOTION_ABUSE;

  public String getEventName() {
    return this.name().toLowerCase();
  }
}
